FROM node:24
WORKDIR /app

RUN corepack enable

COPY package.json yarn.lock .yarnrc.yml next.config.ts ./

RUN yarn install --immutable

COPY . .

EXPOSE 3000

CMD ["yarn", "dev", "--hostname", "0.0.0.0", "--port", "3000"]