FROM node:22-alpine

WORKDIR /app

RUN corepack enable

COPY package.json yarn.lock .pnp.cjs .pnp.loader.mjs ./
COPY .yarn ./.yarn

RUN yarn install --immutable

COPY . .

EXPOSE 3000

CMD ["yarn", "dev", "--hostname", "0.0.0.0", "--port", "3000"]