FROM python:3.14

COPY --from=docker.io/astral/uv:latest /uv /uvx /bin/

WORKDIR /app

COPY ./requirements.txt .

RUN uv sync --frozen

COPY . .

CMD ["fastapi" , "dev", "--host", "0.0.0.0", "--port", "80" ]


